Temporarily pin versions of pipenv and coverage
Pipenv:

Because with 2021.11.5.post0 all dependencies were seemingly installed, but then `pipenv run ./manage.py ...` would fail because it couldn't find Django in the virtualenv.

Thanks to https://twitter.com/hugovk/status/1457711810967183363

----

Coverage:

Was getting these errors when running coveralls:

    ImportError: cannot import name 'Reporter' from 'coverage.report' 

    TypeError: __init__() missing 1 required positional argument: 'name'

Which I think is because coverage 6.x has changed and coveralls has problems with it. So, specifically adding coverage < 6.